
package Horcado;

import java.awt.Color;

/**
 * <p>Juego del horcado</p>
 * @version 1.0
 * @author Juan Manuel Rodriguez Perez
 */
public class Fondo extends javax.swing.JPanel {

    /**
     * Creates new form Fondo
     */
    public Fondo() {
        initComponents();
    }

    /**
     * Metodo para cambiar el fondo
     * @param opcion 
     */
    public void cambiarFondo(int opcion){     
        switch (opcion) {
            case 1:
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Horcado/fondoAhorcado.jpg")));
                jLabel1.setOpaque(false);
                jLabel1.repaint();
                break;
            case 2:
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Horcado/fondoAhorcado2.jpg")));
                jLabel1.setOpaque(false);
                jLabel1.repaint();
                break;
            case 3:
                jLabel1.setIcon(null);
                jLabel1.setOpaque(true);
                jLabel1.setBackground(Color.GRAY);
                break;
            case 4:
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Horcado/fondoAhorcado3.jpg")));
                jLabel1.setOpaque(false);
                jLabel1.repaint();
                break;
            case 5:
                jLabel1.setIcon(null);
                jLabel1.setOpaque(true);
                jLabel1.setBackground(Color.pink);
                break;
            case 6:
                jLabel1.setIcon(null);
                jLabel1.setOpaque(true);
                jLabel1.setBackground(Color.cyan);
                break;
            default:
                jLabel1.setIcon(null);
                jLabel1.setOpaque(false);
                break;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1024, 680));
        setPreferredSize(new java.awt.Dimension(1024, 680));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Horcado/fondoAhorcado.JPG"))); // NOI18N
        jLabel1.setToolTipText("contiene imagen de fondo");
        jLabel1.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
