
package Horcado;

/**
 * <p>Juego del horcado</p>
 * @version 1.0
 * @author Juan Manuel Rodriguez Perez
 */

import java.awt.event.KeyEvent;
import javax.swing.InputMap;
import javax.swing.KeyStroke;
import javax.swing.JOptionPane;
import java.io.*;
import sun.audio.*;

public class NuevoJugador extends javax.swing.JDialog {
    //Atributos
   private AplicacionAhorcado aplicacion;
   private InputMap map;
   
    /**
     * Metodo constructor del JDialog Acerca De
     */
    public NuevoJugador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        aplicacion=(AplicacionAhorcado) parent;
        initComponents();
        map =new InputMap();
        map.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, false), "pressed");
        map.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, true), "released");   
        botonAceptar.setInputMap(0, map);
        setLocationRelativeTo(null);
    }

     /**
     * Metodo para reproducir sonido
     */
    private void reproducirSonido(String ruta){
        try{
        InputStream in=new FileInputStream(ruta);
        AudioStream audio = new AudioStream(in);
        AudioPlayer.player.start(audio);
        }catch(Exception exc){
            System.out.println("Error lectura sonido");
        }
    }
    
    //A partir de aqui metodos auto genereados 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();
        labelNombreJugador = new javax.swing.JLabel();
        textNombreJugador = new javax.swing.JTextField();
        botonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Insertar Nuevo Jugador");

        panelContenedor.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Jugador"));

        labelNombreJugador.setText("Nombre Jugador: ");

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNombreJugador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textNombreJugador)
                .addContainerGap())
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(botonAceptar)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreJugador)
                    .addComponent(textNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo del boton aceptar
     * @param evt 
     */
    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
        String nombre = textNombreJugador.getText();
        if(nombre.equals("")){
            nombre="Ninguno";
            reproducirSonido("../Horcado/src/Horcado/WAV/errorAplicacion.wav");
            JOptionPane.showMessageDialog(this, "Debe introducir un nombre correcto", "Nombre vacio", 1);
            NuevoJugador jug = new NuevoJugador(aplicacion, true);
            jug.setVisible(true);
        }else{
        aplicacion.setJugador(nombre);
        }
        this.dispose();
    }//GEN-LAST:event_botonAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JLabel labelNombreJugador;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JTextField textNombreJugador;
    // End of variables declaration//GEN-END:variables
}
